name: Android CI

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  push:
    tags: 
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      working-directory: ./easycontrol
      run: chmod +x gradlew
    - name: Build server and app
      working-directory: ./easycontrol
      run: |
        ./gradlew :server:copyRelease
        ./gradlew :app:assembleRelease
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动使用 GitHub Token
      with:
        upload_url: ${{ github.event.release.upload_url }}  # 动态获取 Release URL
        asset_path: ./easycontrol/app/build/outputs/apk/release/app-release.apk  # APK 路径
        asset_name: EasyControl-v1.0.0.apk  # 自定义文件名
        asset_content_type: application/vnd.android.package-archive
