name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      working-directory: ./easycontrol
      run: chmod +x gradlew
    # - name: Build server
    #   working-directory: ./easycontrol
    #   run: ./gradlew :server:build
    - name: Build server and copy APK
      working-directory: ./easycontrol
      run: ./gradlew :server:copyRelease
    # - name: Copy server to app resources
    #   working-directory: ./easycontrol
    #   run: |
    #     mkdir -p app/src/main/res/raw/
    #     cp server/build/libs/server.jar app/src/main/res/raw/easycontrol_server
    - name: Build Android app
      working-directory: ./easycontrol
      run: ./gradlew :app:assembleDebug
