name: Android CI

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  # push:
  #   tags: 
  #     - 'v*'
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        build-tools-version: "34.0.0"
        platform-version: "34"
    - name: Grant execute permission for gradlew
      working-directory: ./easycontrol
      run: chmod +x gradlew
    - name: Set up signing
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > easycontrol/app/keystore.jks
        chmod 644 easycontrol/app/keystore.jks
    - name: Extract version name
      id: version
      run: |
        VERSION_NAME="${GITHUB_REF#refs/tags/v}"
        echo "APP_VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
        echo "Version: ${VERSION_NAME}"
    - name: Generate version code
      run: |
        DATE_PART=$(date +'%Y%m%d')
        SEQUENCE=$(echo $GITHUB_RUN_NUMBER | rev | cut -c 1-2 | rev)  # 取后两位
        echo "VERSION_CODE=${DATE_PART}${SEQUENCE}" >> $GITHUB_ENV
        echo "VersionCode: ${VERSION_CODE}"
    - name: Build server and app
      working-directory: ./easycontrol
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}  # 注入 Secrets 到环境变量
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        VERSION_NAME: ${{ env.VERSION_NAME }}
        VERSION_CODE: ${{ env.VERSION_CODE }}
      run: |
        ./gradlew :server:copyRelease
        ./gradlew :app:assembleRelease
    - name: Verify APK
      run: |
        ls -lh easycontrol/app/build/outputs/apk/release/
        ${ANDROID_HOME}/build-tools/34.0.0/apksigner verify --print-certs easycontrol/app/build/outputs/apk/release/app-release.apk
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动使用 GitHub Token
      with:
        upload_url: ${{ github.event.release.upload_url }}  # 动态获取 Release URL
        asset_path: ./easycontrol/app/build/outputs/apk/release/app-release.apk  # APK 路径
        asset_name: EasyControl-${{ env.VERSION_NAME }}.apk
        asset_content_type: application/vnd.android.package-archive
